server:
  port: ${PORT:8080}
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
      - text/html
      - text/css
      - application/javascript
      - application/json

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  thymeleaf:
    cache: ${THYMELEAF_CACHE:true}
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 7d
          cache-public: true
  flyway:
    enabled: true

logging:
  level:
    root: INFO
    com.atoolz.htmx: ${APP_LOG_LEVEL:INFO}
