server:
  port: ${PORT:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  thymeleaf:
    cache: false
  flyway:
    enabled: true

logging:
  level:
    root: INFO
    com.atoolz.htmx: DEBUG
